package com.evenliu.db.entity;

public class Danmu {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column danmu.danmu_id
     *
     * @mbggenerated Thu Sep 15 21:40:02 CST 2016
     */
    private Integer danmuId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column danmu.id
     *
     * @mbggenerated Thu Sep 15 21:40:02 CST 2016
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column danmu.danmu
     *
     * @mbggenerated Thu Sep 15 21:40:02 CST 2016
     */
    private String danmu;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column danmu.danmu_id
     *
     * @return the value of danmu.danmu_id
     *
     * @mbggenerated Thu Sep 15 21:40:02 CST 2016
     */
    public Integer getDanmuId() {
        return danmuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column danmu.danmu_id
     *
     * @param danmuId the value for danmu.danmu_id
     *
     * @mbggenerated Thu Sep 15 21:40:02 CST 2016
     */
    public void setDanmuId(Integer danmuId) {
        this.danmuId = danmuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column danmu.id
     *
     * @return the value of danmu.id
     *
     * @mbggenerated Thu Sep 15 21:40:02 CST 2016
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column danmu.id
     *
     * @param id the value for danmu.id
     *
     * @mbggenerated Thu Sep 15 21:40:02 CST 2016
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column danmu.danmu
     *
     * @return the value of danmu.danmu
     *
     * @mbggenerated Thu Sep 15 21:40:02 CST 2016
     */
    public String getDanmu() {
        return danmu;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column danmu.danmu
     *
     * @param danmu the value for danmu.danmu
     *
     * @mbggenerated Thu Sep 15 21:40:02 CST 2016
     */
    public void setDanmu(String danmu) {
        this.danmu = danmu;
    }
}