package com.evenliu.db.dao;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.evenliu.db.entity.Danmu;
import com.evenliu.db.entity.Seckill;

public interface DanmuMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table danmu
     *
     * @mbggenerated Thu Sep 15 21:40:02 CST 2016
     */
    int deleteByPrimaryKey(Integer danmuId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table danmu
     *
     * @mbggenerated Thu Sep 15 21:40:02 CST 2016
     */
    int insert(Danmu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table danmu
     *
     * @mbggenerated Thu Sep 15 21:40:02 CST 2016
     */
    int insertSelective(Danmu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table danmu
     *
     * @mbggenerated Thu Sep 15 21:40:02 CST 2016
     */
    Danmu selectByPrimaryKey(Integer danmuId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table danmu
     *
     * @mbggenerated Thu Sep 15 21:40:02 CST 2016
     */
    int updateByPrimaryKeySelective(Danmu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table danmu
     *
     * @mbggenerated Thu Sep 15 21:40:02 CST 2016
     */
    int updateByPrimaryKey(Danmu record);
    
    List<Danmu> queryAll(@Param("offset")int offset,@Param("limit")int limit);
}