package com.evenliu.db.dao;

import org.apache.ibatis.annotations.Param;

import com.evenliu.db.entity.SuccessKilled;
import com.evenliu.db.entity.SuccessKilledKey;

public interface SuccessKilledMapper {
	
	/**
	 * 更具id查询successkillEd并携带秒杀对象实体
	 * @param seckillId
	 * @return
	 */
	SuccessKilled queryByIdWithSeckill(@Param("seckillId")long seckillId,@Param("userPhone")long userPhone);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table success_killed
     *
     * @mbggenerated Mon Aug 22 10:06:00 CST 2016
     */
    int deleteByPrimaryKey(SuccessKilledKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table success_killed
     *
     * @mbggenerated Mon Aug 22 10:06:00 CST 2016
     */
    int insert(SuccessKilled record);

    /**
     * 联合主键可以过滤重复
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table success_killed
     *
     * @mbggenerated Mon Aug 22 10:06:00 CST 2016
     */
    int insertSelective(SuccessKilled record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table success_killed
     *
     * @mbggenerated Mon Aug 22 10:06:00 CST 2016
     */
    SuccessKilled selectByPrimaryKey(SuccessKilledKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table success_killed
     *
     * @mbggenerated Mon Aug 22 10:06:00 CST 2016
     */
    int updateByPrimaryKeySelective(SuccessKilled record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table success_killed
     *
     * @mbggenerated Mon Aug 22 10:06:00 CST 2016
     */
    int updateByPrimaryKey(SuccessKilled record);
}